DROP TABLE IF EXISTS employee;

CREATE TABLE EMPLOYEE (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  FIRST_NAME VARCHAR(255) NOT NULL,
  LAST_NAME VARCHAR(255) NOT NULL,
  DATE_OF_BIRTH DATE NOT NULL,
  ADDRESS_LINE_1 VARCHAR(255) NOT NULL,
  ADDRESS_LINE_2 VARCHAR(255),
  CITY VARCHAR(255) NOT NULL,
  STATE VARCHAR(255) NOT NULL,
  COUNTRY VARCHAR(255) NOT NULL,
  ZIP_CODE VARCHAR(255) NOT NULL
);


